version: "3.1"
services:


  database:
    image: mysql:5.7
    volumes:
      - ./main/resources:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=Portly"
  make:
    build: .
    command: sh -c "apk add bash && bash ./wait-for-it.sh database:3306 --timeout=20 -- java -jar app.jar"
    ports:
      - "8080:8080"
    